apiVersion: v1
kind: Service

metadata:
  name: owserver 

spec:
  selector:
    app: onewire 
  ports:
    - name: tcp
      port: 4304
---
apiVersion: v1
kind: Service

metadata:
  name: owhttpd

spec:
  selector:
    app: onewire
  ports:
    - name: tcp
      port: 2121
---
apiVersion: v1
kind: Service

metadata:
  name: onewire-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9401"
spec:
  selector:
    app: onewire
  ports:
    - name: tcp
      port: 9401
