apiVersion: apps/v1beta1 
kind: Deployment

metadata:
  name: claymore-dual-miner
spec:
  replicas: 1 
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: claymore-dual-miner
    spec:
      containers:
        - name: claymore-dual-miner 
          securityContext:
            privileged: true
          resources:
            limits:
              alpha.kubernetes.io/nvidia-gpu: 6
          image: bugroger/claymore-dual-miner:10.0
          args:
            - -epool 
            - stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 
            - -ewal
            - 3BeJnixzKegDCxjGf8BJgw9UWWazoTATxH 
            - -eworker 
            - wupse 
            - -epsw 
            - x 
            - -esm 
            - "3"
            - -estale 
            - "0"
            - -dcoin 
            - dcr 
            - -dpool 
            - stratum+tcp://decred.eu.nicehash.com:3354
            - -dwal 
            - 3BeJnixzKegDCxjGf8BJgw9UWWazoTATxH 
            - -wd 
            - "1"
            - -allpools 
            - "1"
            - -dcri 
            - "40"
          ports:
            - containerPort: 3333
          volumeMounts:
            - mountPath: /usr/local/nvidia
              name: nvidia 
            - mountPath: /usr/local/cuda
              name: cuda 
        - name: metrics
          image: bugroger/miner-exporter:v201707081032
          ports:
            - containerPort: 9278
        
      volumes:
        - name: nvidia
          hostPath:
            path: /opt/nvidia/current
        - name: cuda
          hostPath:
            path: /opt/cuda/current
