apiVersion: v1
kind: Pod
metadata:
  name: cephfs
spec:
  containers:
    - name: cephfs-rw
      image: ubuntu
      command:
        - sleep
        - "1800"
      volumeMounts:
        - mountPath: "/mnt/data"
          name: data
  volumes:
    - name: data
      cephfs:
        monitors:
          - 192.168.2.2:6789
          - 192.168.2.3:6789
          - 192.168.2.4:6789
        user: admin
        subdir: /plex
        secretRef:
          name: ceph-secret
