apiVersion: v1
kind: ReplicationController
metadata:
  name: ceph-mon-core3

spec:
  replicas: 1
  template:
    metadata:
      labels:
        daemon: ceph-mon
        node: core03
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: 192.168.2.4
      volumes:
        - name: etc-ceph
          hostPath:
            path: /etc/ceph
        - name: var-lib-ceph
          hostPath:
            path: /var/lib/ceph
      containers:
        - name: osd
          image: bugroger/ceph-mon
          volumeMounts:
            - name: var-lib-ceph
              mountPath: /var/lib/ceph
            - name: etc-ceph
              mountPath: /etc/ceph
          env:
            - name: MON_IP
              value: 192.168.2.4
            - name: MON_NAME
              value: core03
          ports:
            - containerPort: 6789
              hostPort: 6789
