apiVersion: v1
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
    - name: cephfs-rw
      image: kubernetes/pause
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: "/mnt/data"
          name: data
  volumes:
    - name: data
      rbd:
        monitors:
          - 192.168.2.2:6789
          - 192.168.2.3:6789
          - 192.168.2.4:6789
        pool: rbd
        image: data
        user: admin
        secretRef:
          name: ceph-secret
        fsType: ext4
