apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: m.ichael.j.schmidt@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-staging
    http01:  {}
