#!/bin/bash

set -e

echo "deluge:deluge:10" >> /config/auth

deluge-console -c /config "config -s move_completed_path /data/completed"
deluge-console -c /config "config -s torrentfiles_location /data/torrentsfiles"
deluge-console -c /config "config -s download_location /data/download"
deluge-console -c /config "config -s autoadd_location /data/autoadd"
deluge-console -c /config "config -s random_port true"

sleep Infinity
