apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume2-14tb-btrfs
spec:
  capacity:
    storage: 14Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.5
    path: "/volume2/SharedMedia"
