apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana 
spec:
  replicas: 1 
  selector:
    app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana 
          image: grafana/grafana:2.5.0
          ports:
            - containerPort: 3000 
          volumeMounts:
            - mountPath: /var/lib/grafana"
              name: data
      volumes:
        - name: data
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /grafana
            user: admin
            secretRef:
              name: ceph-secret
