apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus 
spec:
  replicas: 1 
  selector:
    app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus 
          image: bugroger/prometheus:2
          ports:
            - name: http 
              containerPort: 9090
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus
      volumes:
        - name: prometheus
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /prometheus
            user: admin
            secretRef:
              name: ceph-secret
