apiVersion: v1
kind: ReplicationController
metadata:
  name: sabnzb 
spec:
  replicas: 1 
  selector:
    app: sabnzb
  template:
    metadata:
      labels:
        app: sabnzb
    spec:
      containers:
        - name: sabnzb
          image: timhaak/sabnzbd
          ports:
            - containerPort: 8080
            - containerPort: 9090 
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
      volumes:
        - name: config
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /sabnzb/config
            user: admin
            secretRef:
              name: ceph-secret
        - name: data
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /downloads/sabnzb
            user: admin
            secretRef:
              name: ceph-secret
