apiVersion: v1
kind: ReplicationController
metadata:
  name: sabnzb 
spec:
  replicas: 1 
  selector:
    app: sabnzb
  template:
    metadata:
      labels:
        app: sabnzb
    spec:
      containers:
        - name: sabnzb
          image: timhaak/sabnzbd
          ports:
            - containerPort: 8080
            - containerPort: 9090 
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /mnt/data/downloads/sabnzb
        - name: config
          hostPath: 
            path: /mnt/data/sabnzb/config
