apiVersion: v1
kind: ReplicationController
metadata:
  name: sonarr 
spec:
  replicas: 1 
  selector:
    app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr 
          image: bugroger/sonarr:2.0.0.3573
          ports:
            - containerPort: 8989 
          volumeMounts:
            - mountPath: /volumes/config
              name: config
            - mountPath: /volumes/completed
              name: completed 
            - mountPath: /volumes/media
              name: media
          livenessProbe:
            httpGet:
              path: /system/status
              port: 8989 
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10 
      volumes:
        - name: config
          hostPath:
            path: /mnt/data/sonarr/config
        - name: completed
          hostPath:
            path: /mnt/data/downloads
        - name: media
          hostPath:
            path: /mnt/data/media/tv
