apiVersion: v1
kind: Service

metadata:
  name: cadvisor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: cadvisor
  ports:
    - name: tcp
      port: 8080
