{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kubelet_version",
    "query": "label_values(kube_node_info,kubelet_version)"
   },
   {
    "name": "coreos_version",
    "query": "label_values(kube_node_info,os_image)"
   },
   {
    "name": "kernel_version",
    "query": "label_values(kube_node_info,kernel_version)"
   },
   {
    "name": "docker_version",
    "query": "label_values(kube_node_info,container_runtime_version)"
   }
  ]
 },
 "panels": [
  { "title": "GPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(nvidia_info)" }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "max(avg_over_time(nvidia_temperatures[10m])) by (minor)",
     "legendFormat": "GPU{{minor}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg(nvidia_utilization_gpu) by (minor) ",
     "legendFormat": "GPU{{minor}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "avg(nvidia_utilization_memory) by (minor)",
     "legendFormat": "GPU{{minor}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "avg(nvidia_power_usage) by (minor)",
     "legendFormat": "GPU{{minor}}"
    }
   ]
  },
  { "title": "Miner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Switches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(changes(miner_up[24h])) by (name))"
    }
   ]
  },
  {
   "title": "Miner",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(sum_over_time(miner_up[24h])) by (name) / 1440) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Algorithms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "(sum(sum_over_time(miner_up[24h])) by (name) / 1440) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Algorithms",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(count_over_time(miner_rates_total[24h])) by (algorithm) / ignoring(algorithm) group_left sum(count_over_time(miner_rates_total[24h]))) > 0",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "Algorithms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "(sum(count_over_time(miner_rates_total[24h])) by (algorithm) / ignoring(algorithm) group_left sum(count_over_time(miner_rates_total[24h]))) > 0",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - ((1440 - sum(sum_over_time(miner_up[24h]))) / 1440)"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Daily Profit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(miningpoolhub_balance{symbol=\"ETH\",wallet=\"normal\"}[24h])) by (symbol)  * 24 * 60 * 60 * (1 / sum(miningpoolhub_price) by (symbol))"
    }
   ]
  },
  {
   "title": "Payout Limit",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "miningpoolhub_balance{coin=\"ethereum\",wallet=\"normal\",status=\"confirmed\"} / 0.1"
    }
   ]
  },
  {
   "title": "Month",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(miningpoolhub_balance{symbol=\"ETH\",wallet=\"normal\"}[24h])) by (symbol)  * 24 * 60 * 60 * (1 / sum(miningpoolhub_price) by (symbol))",
     "legendFormat": "Profit"
    }
   ]
  },
  {
   "title": "Pool Balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "sum(miningpoolhub_balance_converted) by (symbol)",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Next Payout",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "(0.1 - miningpoolhub_balance{coin=\"ethereum\",wallet=\"normal\",status=\"confirmed\"}) / rate(miningpoolhub_balance{coin=\"ethereum\",wallet=\"normal\",status=\"confirmed\"}[24h])"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    { "expr": "(time() - node_boot_time) " }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "max(avg_over_time(node_hwmon_temp_celsius[10m])) by (sensor)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum(irate(node_cpu{mode=~\"iowait|system|user\"}[5m])) by (cpu) ",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree+node_memory_Buffers+node_memory_Cached)",
     "legendFormat": "Used"
    },
    { "expr": "sum(node_memory_MemTotal)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "expr": "+sum(irate(node_network_receive_bytes[5m]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes[5m]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "content": "<table style=\"width: 100%; border: none\">\n<tr><td style=\"font-weight: bold\">CoreOS</td><td>$coreos_version</td></tr>\n<tr><td style=\"font-weight: bold\">Kernel</td><td>$kernel_version</td></tr>\n<tr><td style=\"font-weight: bold\">Kubernetes</td><td>$kubelet_version</td></tr>\n<tr><td style=\"font-weight: bold\">Docker</td><td>$docker_version</td></tr>\n</table>\n\n\n\n\n"
  },
  {
   "title": "Room",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(onewire_temperatures{address=\"/28.4F94ED060000\"}[10m]) ",
     "legendFormat": "Air"
    },
    {
     "expr": "avg_over_time(onewire_temperatures{address=\"/28.077AAF030000\"}[10m]) ",
     "legendFormat": "PSU"
    }
   ]
  }
 ]
}