---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: burstdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: burst-plots-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8000Gi
