apiVersion: v1
kind: ReplicationController
metadata:
  name: openhab
spec:
  replicas: 1 
  selector:
    app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      hostNetwork: true
      containers:
        - name: openhab 
          image: bugroger/openhab:arm-4
          ports:
            - containerPort: 8080
            - containerPort: 8433
          env:
            - name: ADDONS
              value: org.openhab.binding.http,org.openhab.binding.ntp,org.openhab.binding.knx,org.openhab.io.habmin,org.openhab.binding.zwave,org.openhab.ui.habmin_2.0.0.SNAPSHOT
          volumeMounts:
            - mountPath: /etc/openhab
              name: configurations
            - mountPath: /opt/openhab/logs
              name: logs
            - mountPath: /dev/ttyACM0
              name: zwave
          securityContext:
            privileged: true
      volumes:
        - name: configurations 
          gitRepo:
            repository: https://github.com/BugRoger/configurations.git
            revision: master
        - name: zwave
          hostPath:
            path: /dev/ttyACM0
        - name: logs
          emptyDir: {}
      nodeSelector:
        arch: arm
