apiVersion: v1
kind: ReplicationController
metadata:
  name: plex
spec:
  replicas: 1 
  selector:
    app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        arch: amd64
      containers:
        - name: plex 
          image: wernight/plex-media-server:0.9.14.6
          ports:
            - containerPort: 32400
          volumeMounts:
            - mountPath: "/media"
              name: media
            - mountPath: "/config"
              name: config
      volumes:
        - name: config
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /plex
            user: admin
            secretRef:
              name: ceph-secret
        - name: media
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /media
            user: admin
            secretRef:
              name: ceph-secret


