apiVersion: v1
kind: ReplicationController
metadata:
  name: sonarr 
spec:
  replicas: 1 
  selector:
    app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        arch: amd64
      containers:
        - name: sonarr 
          image: bugroger/sonarr:2.0.0.3573
          ports:
            - containerPort: 8989 
          volumeMounts:
            - mountPath: /volumes/config
              name: config
            - mountPath: /volumes/completed
              name: completed 
            - mountPath: /volumes/media
              name: media
          livenessProbe:
            httpGet:
              path: /system/status
              port: 8989 
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10 
      volumes:
        - name: config
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /sonarr/config
            user: admin
            secretRef:
              name: ceph-secret
        - name: completed
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /downloads
            user: admin
            secretRef:
              name: ceph-secret
        - name: media
          cephfs:
            monitors:
              - 192.168.2.2:6789
              - 192.168.2.3:6789
              - 192.168.2.4:6789
            subdir: /media/tv
            user: admin
            secretRef:
              name: ceph-secret
