apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
  - host: plex.d26a.de
    http:
      paths:
        - path: /
          backend:
            serviceName: plex
            servicePort: 32400
