kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-transcode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
