apiVersion: apps/v1beta1 
kind: Deployment

metadata:
  name: nvidia-settings 
spec:
  replicas: 1 
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: nvidia-settings
    spec:
      hostNetwork: true
      containers:
        - name: nvidia-settings 
          securityContext:
            privileged: true
          image:  bugroger/nvidia-settings:v201803112115
          imagePullPolicy: Always
