apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter

spec:
  template:
    metadata:
      labels:
        node: any
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: prom/node-exporter
          args:
            - -collector.procfs 
            - /host/proc
            - -collector.sysfs 
            - /host/sys 
            - -collector.filesystem.ignored-mount-points 
            - "^/(sys|proc|dev|host|etc)($|/)"
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
            - name: sys
              mountPath: /host/sys
            - name: rootfs
              mountPath: /rootfs
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /
           




